"use client";

// import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { useEffect } from "react";
import gsap from "gsap";
import { ScrollToPlugin } from "gsap/ScrollToPlugin";
import { ScrollTrigger } from "gsap/ScrollTrigger";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

gsap.registerPlugin(ScrollToPlugin, ScrollTrigger);

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    let scrollTween: gsap.core.Tween | null = null;

    const handleWheel = (e: WheelEvent) => {
      e.preventDefault();

      const target = window.scrollY + e.deltaY * 1.2; // multiplier = scroll speed
      const clamped = Math.max(
        0,
        Math.min(target, document.body.scrollHeight - window.innerHeight)
      );

      if (scrollTween) scrollTween.kill();

      scrollTween = gsap.to(window, {
        duration: 1.5,
        scrollTo: clamped,
        ease: "power4.out",
      });
    };

    window.addEventListener("wheel", handleWheel, { passive: false });

    return () => {
      window.removeEventListener("wheel", handleWheel);
    };
  }, []);

  return (
    <html lang="en" className={roboto.className}>
      <body className="bg-gray-900 text-white overflow-x-hidden">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
